// icons: https://icons.getbootstrap.com/
const SEO = {
  title: 'MOGOMI',
  description: 'Invest in the 5 key sectors of Arbitrum with MOGOMI 🚀 Earn yield through staking on the Arbitrum network with our Dapp and Layer 2 Trading Vault 💰 Buy ATG tokens for GLP, Live Grid Trading Bots, Staking, and Governance Liquidity in one 💎',
  keywords: 'MOGOMI, Arbitrum, cryptocurrency investment, decentralized finance, DeFi, yield farming, digital assets, blockchain technology, crypto staking, investment strategy',
  token: "ATG",
  email: "contact@MOGOMI.com",
}
const LINKS = {
  // `"name": { link: "https://", icon?: "bootstrap-icon", color?: "info", external?: true }` or `"name": "link"`
  // "chat with us": { link: "https://MOGOMI.com/", icon: "chat", external: false, color: "default" },
  socialLinks: { // keep the first one as main channel to contact
    discord: "https://discord.com/",
    twitter: "https://twitter.com/",
    github: "https://github.com/",
  },
  navLinks: {
    lend: "https://MOGOMI.com/",
  },
  footerLinks: {
    faq: { to: "/faq", icon: "question-circle" },
    blog: { to: "#", icon: "journal-text" },
    terms: { to: "/terms", icon: "file-earmark-text" },
    policy: { to: "#", icon: "file-earmark-text" },
  },
}
const main = {
  ...SEO,
  ...LINKS,

  // Banner
  banner: {
    text: "Don't miss out on the crypto party, join MOGOMI's Discord server and let's get staking! 🎉🚀",
    button: { name: "Discord", to: "https://discord.com/", icon: "discord" },
  },

  // FAQ page (questions/answers supports markdown)
  faq: [
    {
      question: "🤔 What is MOGOMI?",
      answer: "MOGOMI is like a superhero for your crypto investments - it's a crypto staking network that allows users to invest in the 5 key sectors of Arbitrum and earn yield through staking on the Arbitrum network with our Dapp and Layer2 Trading Vault. Users can also buy ATG tokens for GLP, Live Grid Trading Bots, Staking, and Governance Liquidity in one place.",
    },
    {
      question: "❓ What is Arbitrum?",
      answer: "[Arbitrum](https://arbitrum.io/) is a Layer 2 scaling solution for Ethereum that aims to provide fast and cheap transactions while maintaining the security and decentralization of the Ethereum network.",
    },
    {
      question: "🤝 How do I stake on the Arbitrum network with MOGOMI?",
      answer: "To stake on the Arbitrum network with MOGOMI, you can use our [Dapp](/) and Layer 2 Trading Vault. Simply connect your wallet to the platform and follow the instructions to start staking.",
    },
    {
      question: "💰 What are the benefits of staking on the Arbitrum network with MOGOMI?",
      answer: "Staking on the Arbitrum network with MOGOMI allows you to earn yield on your investment while supporting the security and decentralization of the network. Additionally, you can buy ATG tokens for GLP, Live Grid Trading Bots, Staking, and Governance Liquidity in one place.",
    },
    {
      question: "🪙 What is the ATG token?",
      answer: "The ATG token is the native token of the MOGOMI platform. It can be used for GLP, Live Grid Trading Bots, Staking, and Governance Liquidity.",
    },
    {
      question: "🕵️‍♀️ Is my investment safe on the MOGOMI platform?",
      answer: "Yes, the safety and security of our users' investments is of utmost importance to us. Our platform is built using the latest security protocols and is constantly reviewed by our community and external auditors to ensure its safety. Additionally, our users' investments are secured by smart contracts on the blockchain, which are transparent and immutable. So, you can rest assured that your investment is in safe hands!",
    },
    {
      question: "🤖 What are Live Grid Trading Bots?",
      answer: "Live Grid Trading Bots are advanced trading algorithms that are designed to help users make the most out of their investments. These bots use cutting-edge technology to analyze market trends and make real-time trading decisions. With Live Grid Trading Bots, you can sit back and relax while our bots do the hard work for you.",
    },
    {
      question: "💰 What is GLP?",
      answer: "GLP stands for Governance Liquidity Provider. It is a unique token that can be used to vote on platform decisions and proposals. By holding GLP, you can have a say in the direction of the platform and its future development. Additionally, GLP holders receive a portion of the fees generated by the platform, making it a lucrative investment opportunity.",
    },
    {
      question: "🙋 What if I have more questions?",
      answer: `Curiosity didn't kill the cat, it led it to MOGOMI! Feel free to ask us anything by joining our [${Object.keys(LINKS.socialLinks)[0]}](${Object.values(LINKS.socialLinks)[0]}) channel. We promise we won't bite, we're crypto nerds, not vampires.`,
    },
  ],
  terms:
`By using MOGOMI, you agree to be bound by these Terms and Conditions, including any policies or guidelines incorporated by reference. If you do not agree to these Terms and Conditions, you should not use our platform.

### General

MOGOMI is not a financial advisor and does not provide financial advice. You are responsible for your own investment decisions.

MOGOMI does not guarantee any investment returns or profits.

MOGOMI is not responsible for any losses incurred due to market fluctuations or other factors.

MOGOMI reserves the right to change, modify, or update these Terms and Conditions at any time without prior notice. Your continued use of the platform after such changes constitutes your acceptance of the new Terms and Conditions.

### Staking

Staking on the Arbitrum network with MOGOMI allows you to earn yield on your investment while supporting the security and decentralization of the network.

To stake on the Arbitrum network with MOGOMI, you can use our Dapp and Layer 2 Trading Vault. Simply connect your wallet to the platform and follow the instructions to start staking.

The minimum amount required for staking may vary depending on the specific staking program.

The rewards for staking may vary depending on market conditions and other factors.

### ATG Token

The ATG token is the native token of the MOGOMI platform. It can be used for GLP, Live Grid Trading Bots, Staking, and Governance Liquidity.

The value of the ATG token may fluctuate and is subject to market forces.

ATG tokens are not securities and do not represent ownership in MOGOMI.

ATG tokens may be bought and sold on approved exchanges.

### Disclaimer

MOGOMI is not liable for any damages or losses arising from your use of our platform.

MOGOMI is not liable for any damages or losses arising from your reliance on any information provided on our platform.

MOGOMI is not responsible for any third-party content on our platform.

MOGOMI is not liable for any damages or losses resulting from the failure or delay of any service or transaction.

### Governing Law

These Terms and Conditions shall be governed by and construed in accordance with the laws of the jurisdiction in which MOGOMI operates.

Any dispute arising from these Terms and Conditions shall be resolved through binding arbitration in accordance with the rules of the jurisdiction in which MOGOMI operates.

### Contact Us

If you have any questions about these Terms and Conditions, please contact us at ${SEO.email}.
`
}

module.exports = main;